// Code generated by fizzbee-mbt generator (fizz mbt-scaffold --lang
// rust specs/coordination.fizz); regenerate after changing the spec's
// actions. One local patch: the test gates on `SLEET_MBT` so machines
// without the fizzbee-mbt toolchain skip instead of failing.

// Import the generated traits, adapters, and framework utilities
use super::adapters::{get_test_options, new_coordination_model};
use super::traits::*;

use async_trait::async_trait;
use fizzbee_mbt::error::MbtError;
use fizzbee_mbt::traits::*;
use fizzbee_mbt::types::*;
use fizzbee_mbt::value::*;

/// The Dispatcher routes actions from the MBT framework to the correct Role/Model instance.
/// It wraps the concrete Model implementation.
pub struct CoordinationActionDispatcher<T>
where
    T: CoordinationModel + Send + Sync + 'static,
{
    // The concrete model instance is owned directly
    model: Option<T>,
}

#[async_trait]
impl<T> Model for CoordinationActionDispatcher<T>
where
    T: Model + CoordinationModel + Send + Sync + 'static,
{
    /// Delegates initialization to the inner model instance.
    async fn init(&mut self) -> Result<(), MbtError> {
        self.model
            .as_mut()
            .ok_or_else(|| MbtError::other("Model not found"))?
            .init()
            .await
    }

    /// Delegates cleanup to the inner model instance.
    async fn cleanup(&mut self) -> Result<(), MbtError> {
        self.model
            .as_mut()
            .ok_or_else(|| MbtError::other("Model not found"))?
            .cleanup()
            .await
    }
}

impl<T> CoordinationActionDispatcher<T>
where
    T: CoordinationModel + Send + Sync + 'static,
{
    pub fn new(model: T) -> Self {
        CoordinationActionDispatcher { model: Some(model) }
    }
}

/// Implementation of the framework's core execution contract (`DispatchModel`).
#[async_trait]
impl<T> DispatchModel for CoordinationActionDispatcher<T>
where
    T: CoordinationModel,
    T: Send + Sync + 'static,
{
    async fn execute(
        &self,
        role_id: &RoleId,
        function_name: &str,
        args: &[Arg],
    ) -> Result<Value, MbtError> {
        let inner_model_ref = self.model.as_ref().ok_or_else(|| {
            MbtError::other("Model is not initialized or has been moved out of the dispatcher.")
        })?;

        match role_id.role_name.as_str() {
            // Role actions
            "Node" => {
                let index = role_id.index as usize;

                let roles_vec = inner_model_ref.get_node_roles()?;

                let role_rc = roles_vec.get(index).ok_or(MbtError::other(format!(
                    "{}Role instance not found at index {}",
                    "Node", index
                )))?;

                match function_name {
                    "Beat" => role_rc.action_beat(args).await,
                    "Recompute" => role_rc.action_recompute(args).await,
                    "HandleFence" => role_rc.action_handlefence(args).await,
                    "Crash" => role_rc.action_crash(args).await,
                    "Restart" => role_rc.action_restart(args).await,
                    _ => Err(MbtError::other(format!(
                        "Unknown action '{}' for NodeRole",
                        function_name
                    ))),
                }
            }

            // Top-level actions (role_id.role_name is expected to be empty for top-level)
            "" => match function_name {
                "ExpireCrashed" => inner_model_ref.action_expirecrashed(args).await,
                "Suspect" => inner_model_ref.action_suspect(args).await,
                _ => Err(MbtError::other(format!(
                    "Unknown top-level action: '{}'",
                    function_name
                ))),
            },

            _ => Err(MbtError::other(format!(
                "Unknown role: {}",
                role_id.role_name
            ))),
        }
    }

    fn get_roles(&self) -> Result<Vec<RoleId>, MbtError> {
        let inner_model_ref = self.model.as_ref().ok_or_else(|| {
            MbtError::other("Model is not initialized or has been moved out of the dispatcher.")
        })?;

        let mut all_role_ids = Vec::new();

        // Collect all role IDs

        {
            let roles = inner_model_ref.get_node_roles()?;
            let role_ids: Vec<RoleId> = roles
                .iter()
                .enumerate()
                .map(|(index, _)| RoleId {
                    role_name: "Node".to_string(),
                    index: index as i32,
                })
                .collect();
            all_role_ids.extend(role_ids);
        }

        Ok(all_role_ids)
    }
}

// Use a runtime test macro to allow async operations inside the test function
#[test]
fn test_coordination_model() -> Result<(), MbtError> {
    if std::env::var_os("SLEET_MBT").is_none() {
        eprintln!("note: SLEET_MBT unset; skipping model-based test");
        return Ok(());
    }
    let model = new_coordination_model();

    let dispatcher = CoordinationActionDispatcher::new(model);

    // Executes model-based test traces.
    fizzbee_mbt::run_mbt_test(dispatcher, get_test_options())?;

    Ok(())
}
