// Code generated by fizzbee-mbt generator (fizz mbt-scaffold --lang
// rust specs/coordination.fizz); regenerate after changing the spec's
// actions. One local patch: `#[async_trait]` on `CoordinationModel`,
// which the generator omits, leaving its async methods non-Send.

use async_trait::async_trait;
use fizzbee_mbt::error::MbtError;
use fizzbee_mbt::traits::*;
use fizzbee_mbt::types::Arg;
use fizzbee_mbt::value::Value;
use std::sync::Arc;

// Role traits

#[async_trait]
pub trait NodeRole: AsyncRole {
    async fn action_beat(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_recompute(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_handlefence(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_crash(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_restart(&self, args: &[Arg]) -> Result<Value, MbtError>;
}

// Model trait
#[async_trait]
pub trait CoordinationModel: Model {
    // R0 is the trait for the NodeRole
    type R0: NodeRole;
    fn get_node_roles(&self) -> Result<Vec<Arc<Self::R0>>, MbtError>;

    // Top-level actions
    async fn action_expirecrashed(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_suspect(&self, args: &[Arg]) -> Result<Value, MbtError>;
}
